name: 构建应用程序

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'  # 匹配所有版本标签
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --user
      
      - name: 构建应用
        run: python github_build.py
      
      - name: 打包构建产物
        run: |
          cd dist
          zip -r FbAutoTool-macOS.zip FbAutoTool
          cd ..
      
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: FbAutoTool-macOS
          path: dist/FbAutoTool-macOS.zip
          retention-days: 7

  build-windows:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: utf-8 # 设置Python IO编码为UTF-8
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --user
        env:
          PYTHONIOENCODING: utf-8
      
      - name: 构建应用
        run: python github_build.py
        env:
          PYTHONIOENCODING: utf-8
      
      - name: 打包构建产物
        run: |
          cd dist
          powershell Compress-Archive -Path FbAutoTool.exe -DestinationPath FbAutoTool-Windows.zip
          cd ..
      
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: FbAutoTool-Windows
          path: dist/FbAutoTool-Windows.zip
          retention-days: 7
  
  # 创建发布版本（仅在打标签时）
  create-release:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: 获取macOS构建产物
        uses: actions/download-artifact@v3
        with:
          name: FbAutoTool-macOS
          path: ./
      
      - name: 获取Windows构建产物
        uses: actions/download-artifact@v3
        with:
          name: FbAutoTool-Windows
          path: ./
      
      - name: 创建Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            FbAutoTool-macOS.zip
            FbAutoTool-Windows.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 