name: Windows Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest
    timeout-minutes: 45 # 延长超时时间

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.11" # 指定精确版本
          architecture: "x64" # 明确指定架构

      - name: Install system dependencies
        run: |
          # 强制安装指定版本pip
          C:\hostedtoolcache\windows\Python\3.10.11\x64\python.exe -m pip install --disable-pip-version-check --no-input "pip==23.3.2" --no-warn-script-location
          C:\hostedtoolcache\windows\Python\3.10.11\x64\python.exe -m pip install "wheel==0.40.0" "setuptools==68.2.2" --no-warn-script-location

      - name: Install project dependencies
        run: |
          # 确保Pillow优先安装
          C:\hostedtoolcache\windows\Python\3.10.11\x64\python.exe -m pip install "Pillow==10.2.0" --no-cache-dir
          # 使用错误消息中指定的确切命令
          C:\hostedtoolcache\windows\Python\3.10.11\x64\python.exe -m pip install -r requirements.txt --user
        env:
          PYTHONIOENCODING: utf-8

      - name: Generate icon file
        run: |
          if (-not (Test-Path app.ico)) {
              Write-Output "生成临时图标..."
              C:\hostedtoolcache\windows\Python\3.10.11\x64\python.exe -c "from PIL import Image; img = Image.new('RGBA', (256,256), (0,0,0,0)); img.save('app.ico', format='ICO')"
          }

      - name: Build with PyInstaller
        env:
          PYTHONUTF8: 1
        run: |
          C:\hostedtoolcache\windows\Python\3.10.11\x64\python.exe -m pyinstaller --noconfirm --clean --onefile `
            --name FbAutoTool-Windows `
            --add-data "main.gui;." `
            --hidden-import task_utils `
            --hidden-import fb_billing_operations `
            --icon app.ico `
            --runtime-tmpdir . `
            main.gui

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fb-auto-tool-windows
          path: |
            dist/
            app.ico
          retention-days: 7

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            build/
            dist/
