name: GUI Build Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller tkinter selenium requests

      - name: Build GUI executable
        run: |
          pyinstaller --onefile --noconsole --name FbAutoTool \
            --add-data="main.gui:." \
            --hidden-import=task_utils \
            --hidden-import=fb_billing_operations \
            main.gui

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fb-auto-tool
          path: dist/
