name: 广告管理工具自动化构建

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-windows:
    name: 构建Windows应用
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: 检出代码
        uses: actions/checkout@v4.1.1

      - name: 缓存Python依赖
        uses: actions/cache@v3
        with:
          path: |
            ~\AppData\Local\pip\Cache
            ~\AppData\Local\pypoetry\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 设置Python环境
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: 安装系统依赖
        run: |
          choco install googlechrome -y --force
          $chromePath = "${env:ProgramFiles(x86)}\Google\Chrome\Application"
          echo "Chrome路径: $chromePath"
          echo "$chromePath" >> $env:GITHUB_PATH

      - name: 安装Python依赖
        run: |
          python -m pip install --upgrade pip
          pip cache dir  # 显示缓存目录用于调试
          pip install -r requirements.txt --verbose

      - name: 执行打包
        run: |
          if not exist app_icon.ico (echo "##[error]缺少图标文件app_icon.ico" && exit 1)
          pyinstaller --version
          pyinstaller build.spec --onefile --noconsole --log-level DEBUG
          7z a -tzip FacebookAdManager.zip .\dist\*

      - name: 上传构建产物
        uses: actions/upload-artifact@v4.3.3
        with:
          name: FacebookAdManager
          path: FacebookAdManager.zip
          retention-days: 7
