name: 广告管理工具自动化构建

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-windows:
    name: 构建Windows应用
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - name: 检出代码
      uses: actions/checkout@v4.1.1

    - name: 缓存Python依赖
      uses: actions/cache@v3.3.2
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: 设置Python环境
      uses: actions/setup-python@v5.1.0
      with:
        python-version: "3.10"
        architecture: "x64"

    - name: 安装系统依赖
      run: |
        choco install googlechrome -y
        $chromePath = "${env:ProgramFiles(x86)}\Google\Chrome\Application"
        echo "$chromePath" >> $env:GITHUB_PATH

    - name: 安装Python依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 执行打包
      run: |
        if not exist app_icon.ico (echo "##[error]缺少图标文件app_icon.ico" && exit 1)
        pyinstaller build.spec --onefile --noconsole
        Compress-Archive -Path dist\* -DestinationPath FacebookAdManager.zip

    - name: 上传构建产物
      uses: actions/upload-artifact@v4.3.3
      with:
        name: FacebookAdManager
        path: dist/FacebookAdManager.zip
        retention-days: 7