name: 广告管理工具自动化构建

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: x64

      - name: 安装依赖
        run: |
          choco install 7zip -y
          pip install -r requirements.txt

      - name: 执行打包
        run: |
          pyinstaller build.spec --clean
          if (-not (Test-Path .\dist\)) {
            Write-Error "构建失败，dist目录不存在"
            exit 1
          }
          Get-ChildItem -Path .\dist -Recurse | Format-Table FullName
          # Windows系统生成exe
          if ($env:RUNNER_OS -eq "Windows") {
            # 验证生成路径
            $exePath = ".\dist\FacebookAdManager.exe"
            if (-not (Test-Path $exePath)) {
              Write-Error "EXE文件未生成"
              exit 1
            }
            # 重命名并压缩
            Rename-Item -Path $exePath -NewName "FacebookAdManager-${{ github.run_number }}.exe"
            7z a FacebookAdManager-${{ github.run_number }}.zip ".\dist\FacebookAdManager-${{ github.run_number }}.exe"
          }
          # Linux系统生成可执行文件
          elseif ($env:RUNNER_OS -eq "Linux") {
            mv ./dist/FacebookAdManager ./dist/FacebookAdManager-${{ github.run_number }}
            tar -czvf FacebookAdManager-${{ github.run_number }}.tar.gz -C ./dist FacebookAdManager-${{ github.run_number }}
          }
          # macOS系统生成可执行文件
          else {
            mv ./dist/FacebookAdManager ./dist/FacebookAdManager-${{ github.run_number }}
            zip -r FacebookAdManager-${{ github.run_number }}.zip ./dist/FacebookAdManager-${{ github.run_number }}
          }

      - name: 上传成品
        uses: actions/upload-artifact@v4
        with:
          name: FacebookAdManager-${{ runner.os }}
          path: |
            FacebookAdManager-*
          retention-days: 7
